### ISSUE TITLE
Overwrite of logged in user

### ISSUE THREAD

**Issue by KilakwaBT** [mecachisenros/cf-civicrm#111]
I have a form that is can only be accessed by logged in users. It is designed to add resources to a group for a directory. When the user completes the form users contact record is changed. The name, data collected on the form and more importantly the contact type is changed. There is one processor which is setup to add the organization. The Auto Populate checkbox is not checked.

**Comment by KilakwaBT** [comment]
I added hidden fields for the first name, last name & email of the logged in contact and linked them to contact processor 1 with auto populate enabled. I switched the Org Contact to contact 2. This seems to have corrected the issue.

**Comment by mecachisenros** [comment]
@KilakwaBT if I understand correctly what you are saying is that the logged in user auto-populates the form regardless if the Auto Populate checkbox is enabled or not, and therefore overriding its own contact data?

**Comment by mecachisenros** [comment]
@KilakwaBT can you test latest `dev` branch including this commit 77d70ca75a32c4ec498e26d6c5c9bc93ae56e4b4?

**Comment by KilakwaBT** [comment]
@mecachisenros I just tested and the issue seems to be resolved in the latest dev branch

The issue was not quite that the form was auto populated but the logged in user was edited as opposed to a new contact being created. My quick fix turned out helpful as we added an activity so we knew when a logged in user added a new organization. 

Thanks!!!

**Comment by andyburnsco** [comment]
We do not use the auto populate function. However, does this resolve the bug I had thought was reported a few months back with logged in users getting their CRM record overwritten?
