### ISSUE TITLE
CiviCRM Contact Reference Field not populating for anonymous user

### ISSUE THREAD

**Issue by elizolivares** [mecachisenros/cf-civicrm#112]
This is for CiviCRM 5.11.0, Wordpress 5.1.1, Caldera Forms 1.8.4, and Caldera Forms CiviCRM 1.0.2.

We have a form that collects name, phone number, email address, and employer. The Employer field is set to 'CiviCRM Contact reference', and the contact type is set to 'Organization'. When logged in, viewing the form presents no issues and the employer field auto populates from organizations in Civi. Accessing the site as an anonymous user, when using the form the employer field does not auto-populate with anything.

Is there something that I am missing here? A permission for anonymous users that needs to be set?

**Comment by mecachisenros** [comment]
@elizolivares Auto-population only works for logged in users or users that access the form via a checksum, as long as the _Auto populate contact data..._ setting is enabled, also note that this functionality it's only possible for the first contact (the contact that submits the form, at least for now).

For an anonymous user the Contact Reference field should allow the user to search for Organisations, does that not work?
