### ISSUE TITLE
Adding Participant Processor prevents expansion of Contact Processor tabs

### ISSUE THREAD

**Issue by clement888** [mecachisenros/cf-civicrm#115]
**Describe the bug**
Tabs below Contact Type does not expand when clicked after Participant Processor is added to form

**To Reproduce**
1. Create Form with Contact Processor
2. Click tabs below Contact Type (e.g Contact Standard Fields) to expand fields for editing
3. Tab expands fields under Contact Standard Fields
4. Add Participant Processor & save form
5. Contact Processor can still expand upon clicking
6. Refresh browser at this page
7. Click tab again and there is no expansion (nothing happens)
8. Remove Participant Processor & save form
9. Refresh page
10. Click Contact Processor's tabs below Contact Type and now it expands as before

**Expected behavior**
Contact Standard Fields should expand to its fields regardless of even when Participant Processor is added

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
- Browser Chrome & Safari
WordPress Version: 5.0.4PHP Version: 7.2.19-0ubuntu0.18.04.1MySQL Version: 5.7.26Caldera Forms Version: 1.8.5WP_DEBUG:
Caldera-CIVICRM v1.0.2

**Comment by clement888** [comment]
A screen shot of the above.  this happens after you save the form and wanted to Edit it again from Caldera Form.
![p1](https://user-images.githubusercontent.com/37096892/61103243-c861fc00-a4a3-11e9-8b05-4f27ecc40bcb.png)

**Comment by mecachisenros** [comment]
@clement888 can you test the latest release and let me know if the issue still persists?

There was a case where jQuery wouldn't be available but used in the processor template, which would break the UI as you described, and it should be fixed in the latest release.

**Comment by clement8888** [comment]
@mecachisenros I am happy to report this update resolved the issue. Thanks!
