### ISSUE TITLE
Adding of 2nd Participant Processor

### ISSUE THREAD

**Issue by clement888** [mecachisenros/cf-civicrm#116]
Is it possible to add a second or more Participant Processor to be linked to contacts captured in the form ?  I have tried adding a second Participant Processor and upon saving the form and  refreshing there are no more fields in the 2nd Participant Processor except for a Remove Processor button.  Thanks.

WordPress Version: 5.0.4PHP Version: 7.2.19-0ubuntu0.18.04.1MySQL Version: 5.7.26Caldera Forms Version: 1.8.5WP_DEBUG:

**Comment by danaskallman** [comment]
@clement888 can you add screenshots? You are able to use multiple participant processors so it'll be helpful to see what you have in place? 

Also do you have the latest version of repo on master of this plugin?

**Comment by clement888** [comment]
@danaskallman thanks for looking into this.  i tried a new form after downloading the latest version from github and the same problem remains.  i can create the form and processor (2 contacts and 2 participants) and all works well.  when i save the form and get back to it again, the participant processor would become like this screenshot:
![p2](https://user-images.githubusercontent.com/37096892/61103080-3b1ea780-a4a3-11e9-9814-fd6fb7204657.png)

i have also posted another related problem to this, when i try to click on the boxes under Contact Processor, it doesn't expand until i remove the Participant processors and re-enter this again through the Form link.  i will place the screenshot for this in the other post.  thanks.

**Comment by mecachisenros** [comment]
@clement888 I believe this is related to #115, if you can test latest release would be great, if the issue persists please report back any browser's console errors.

**Comment by clement8888** [comment]
@mecachisenros I am happy to report this update resolved the issue. Thanks!
