### ISSUE TITLE
File upload setting not displayed in french

### ISSUE THREAD

**Issue by Kwagga-Quagga** [mecachisenros/cf-civicrm#124]
Hi
thank's for this plug-in it has a great potential ! 

**Describe the bug**

Since the release following  #31, it is possible to attatche file to various Civicrm core and custom field.

To do so, one have to check "CiviCRM File Upload" in the form fiel setting, however this checkbox do no apead when wordpress language is french.

**To Reproduce**

install wordpress 5.2.3 in french
install civicrm (still set to its original english language)
install the needed modules
create a from with one of the templates provided with the actual module

**Expected behavior**
have the option available in any language

**Screenshots**

![Capture du 2019-09-17 13-34-28](https://user-images.githubusercontent.com/49561217/65038489-5a78fb80-d950-11e9-92c6-c4d12db74e13.png)
![Capture du 2019-09-17 13-35-41](https://user-images.githubusercontent.com/49561217/65038495-5d73ec00-d950-11e9-960b-0973090449ed.png)

**Desktop (please complete the following information):**
 - OS: stretch 9.4
 - Browser : firefox esr
 - Version 60.9.0

**Additional context**
wordpress : 5.2.3
civicrm : 5.17.4
caldera form : 1.8.7
CF civicrm : 1.0.4

**Comment by mecachisenros** [comment]
👍

**Comment by Kwagga-Quagga** [comment]
:+1: 

Thank's
