### ISSUE TITLE
File upload setting not offered with advanced file uploader

### ISSUE THREAD

**Issue by Kwagga-Quagga** [mecachisenros/cf-civicrm#125]
Hi
thank's for this plug-in it has a great potential ! 

**Describe the bug**

Since the release following  #31, it is possible to attatch file to various Civicrm core and custom field using both the file uploader and the advanced file uploader.

However the advanced file uploader setting do not offre the "civicrm file upload option", and the processor, both activity and note do not to use the advanced file uploader a a source 

**To Reproduce**

install wordpress 5.2.3
install civicrm
install the needed modules
create a from with one of the templates provided with the actual module and use the activity processor

**Expected behavior**
be able to use the advanced file uploader

**Screenshots**
![Capture du 2019-09-17 13-46-52](https://user-images.githubusercontent.com/49561217/65039115-c9a31f80-d951-11e9-965d-3efdf2e9fd07.png)

![Capture du 2019-09-17 13-47-34](https://user-images.githubusercontent.com/49561217/65039102-c4de6b80-d951-11e9-9487-c6367495f8ce.png)

![Capture du 2019-09-17 13-57-52](https://user-images.githubusercontent.com/49561217/65039724-31a63580-d953-11e9-9b12-9a6055829d9c.png)

**Desktop (please complete the following information):**
 - OS: stretch 9.4
 - Browser : firefox esr
 - Version 60.9.0

**Additional context**
wordpress : 5.2.3
civicrm : 5.17.4
caldera form : 1.8.7
CF civicrm : 1.0.4

**Comment by mecachisenros** [comment]
@Kwagga-Quagga thank you for reporting, the plugin does not yet integrate with the Advanced File fields **2.0**, you can use the File fields version 1.0 meanwhile, those should work as expected.

**Comment by mecachisenros** [comment]
@Kwagga-Quagga this should now be fixed (via a1be8e4e544bbd35a652cf8d861d5c6c2e03a8bf) and it will be included in the next release, if you can test the latest `dev` branch and confirm it would be great.

**Comment by Kwagga-Quagga** [comment]
> @Kwagga-Quagga this should now be fixed (via [a1be8e4](https://github.com/mecachisenros/cf-civicrm/commit/a1be8e4e544bbd35a652cf8d861d5c6c2e03a8bf)) and it will be included in the next release, if you can test the latest `dev` branch and confirm it would be great.

Hi I just tested the dev version and the new release 1.0.5, work's great ! 
Thank's
