### ISSUE TITLE
Conditionally add to group 

### ISSUE THREAD

**Issue by hcallens** [mecachisenros/cf-civicrm#126]
Is it possible to add a contact to a group based on the chosen option?

E.g. I have a language choice field where the user can check either one or both languages. If choice A is made the person is to be added to group A, if choice B is made then he is added to group B, and if he chooses both he is added to both groups.

Can this be done?

**Comment by danaskallman** [comment]
@hcallens yeah, you would use the processor conditions to manage when the group processor is used based on a selection. Here's [docs](https://github.com/mecachisenros/cf-civicrm/blob/master/docs/overview.md#conditions) reference.
