### ISSUE TITLE
Pay by check

### ISSUE THREAD

**Issue by lyonsdigital** [mecachisenros/cf-civicrm#128]
I'm stymied. I need to generate a contribution invoice for CiviCRM and my client offers the options to pay later by check or pay now by credit card. 

Do I need separate contribution processors and conditions for each payment scenario? How do I pass the pay later back to CiviCRM?

Since a manager is processing recertification for multiple contacts, should I be using the order or contribution processor? Sorry for all the questions, but I am very confused right now.

**Comment by mecachisenros** [comment]
@lyonsdigital 

1. In your form add a Radio field (Payment method), in the field settings click _Bulk insert/Preset_ and select `CiviCRM Payment Methods` delete the lines that are not `Credit Card` and `Check`, so you end up with to lines like this:
```
1|Credit Card
4|Check
``` 
Then click _Insert Options_.

2. In the Order processors settings check the box _Use Payment Method mapped field_, you'll see a new input right below the checkbox, map the Radio field you've created (Payment method), then set the _Is Pay Later_ setting to _Check_.

3. Add a conditional to your Payment processor to only be used when Credit Card is selected.

**Comment by lyonsdigital** [comment]
Looks good until I submit. Then I get:
'Pay later by check' is not a valid option for field payment_instrument_id

#0 /home/fpptaweb/public_html/wp-content/plugins/cf-civicrm/processors/order/class-order-processor.php(205): civicrm_api3('Order', 'create', Array)
#1 /home/fpptaweb/public_html/wp-content/plugins/caldera-forms/classes/core.php(3425): CiviCRM_Caldera_Forms_Order_Processor->processor(Array, Array, '_cf_process_5db...')
#2 /home/fpptaweb/public_html/wp-content/plugins/caldera-forms/classes/core.php(5203): Caldera_Forms::process_submission()
#3 /home/fpptaweb/public_html/wp-content/plugins/caldera-forms/classes/core.php(3821): Caldera_Forms::process_form_via_post()
#4 /home/fpptaweb/public_html/wp-includes/class-wp-hook.php(286): Caldera_Forms->cf_init_system('')
#5 /home/fpptaweb/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /home/fpptaweb/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#7 /home/fpptaweb/public_html/wp-settings.php(546): do_action('wp_loaded')
#8 /home/fpptaweb/public_html/wp-config.php(88): require_once('/home/fpptaweb/...')
#9 /home/fpptaweb/public_html/wp-load.php(37): require_once('/home/fpptaweb/...')
#10 /home/fpptaweb/public_html/wp-blog-header.php(13): require_once('/home/fpptaweb/...')
#11 /home/fpptaweb/public_html/index.php(17): require('/home/fpptaweb/...')
#12 {main}

What did I miss?

**Comment by lyonsdigital** [comment]
Awesome! I had a small problem following directions but I figured it out. Thank you so much!!

**Comment by lyonsdigital** [comment]
Thanks for all the help on this. It looks like everything is processing nicely. It looks like the line item information is passed to the Caldera outgoing email but is not passed to the CiviCRM invoice. Is that correct or should the line item detail be appearing in the CiviCRM invoice?

**Comment by mecachisenros** [comment]
@lyonsdigital all line items should appear in the invoice, what CiviCRM version are you on?

**Comment by lyonsdigital** [comment]
I'm on 5.13.4. I've created a page to recertify individuals. I'm getting an email with a long list of names who were recertified. I have an attatched CSV with the same information. However, it appears that the list is not transcribed to the invoice in CiviCRM. It would be nice to have that list of five names or fewer on the invoice for the member organization to see who they are paying to certify. The client is complaining that even though they have the information, it's not presented in an easy enough way to easily read.

**Comment by mecachisenros** [comment]
You need to upgrade to CiviCRM v5.16+ or include this patch civicrm/civicrm-core/pull/13477

**Comment by lyonsdigital** [comment]
Thank you again
