### ISSUE TITLE
Event processor generates errors on events that are already registered

### ISSUE THREAD

**Issue by kapn1966** [mecachisenros/cf-civicrm#130]
I have a form which holds event names in a drop-down and has a processor for each event watching the dropdown. As I understand it, the processor is supposed to be triggered by the form submission. I have a condition set on each processor that has it respond only to a particular choice on the drop down. From the standpoint of doing the registration, this works as expected. However, if any registrations already exist, an error is handed back from CiviCRM to the form processor when the page loads as if the page just tried to register the user for the event. Since the form page is just opening and has not been submitted, this seems like bad behaviour. Is the processor trying every event on spec? Any idea what is happening here? it is certainly something that will confuse users.

The following screenshot shows a fresh page load from the base URL (not a refresh of a submitted page). You can see the blank form and the errors.

![Screenshot_2019-11-04 Conference 2019 – Thursday – CESBA Members Events](https://user-images.githubusercontent.com/36196908/68142626-d37ee300-fefd-11e9-991d-f35279a7f1cf.png)

**Comment by mecachisenros** [comment]
@kapn1966 those are _warnings_ (not errors) based on the Event configuration, i.e. if you are already registered Civi won't let you re-register unless the _Same email address?_ setting is enabled on the Event, CFC replicates this behaviour and shows the warning/info boxes letting you know for what events you are already registered. 

This happens for logged in users and users that hit the form via a checksum.

**Comment by kapn1966** [comment]
Understood. At first I thought that the page was somehow re-posting a request that was triggering this. 
The part that is strange and annoying is that the form has not been submitted. I have simply loaded a page that has a form in it. Nothing has been selected. There is simply the possibility that someone might pick a duplicate event and submit the form. Surely this is not reasonable behaviour?

**Comment by mecachisenros** [comment]
> Surely this is not reasonable behaviour?

@kapn1966 I see your point, but and that's CiviCRM's behaviour, if you registered for an event it won't let you re-register unless the mentioned setting is enabled.

If you just want to get rid of the warnings, you could remove them from a plugin or your child theme like so:
``` php
add_filter( 'caldera_forms_get_form', function( $form ) {
  remove_filter(
    'caldera_forms_render_get_form',
    [ caldera_forms_civicrm()->processors->processors['participant'], 'pre_render' ]
  );
  return $form;
} );
```
**Note**: removing this filter will only remove the warnings (for logged in/checksum users) when the form is loaded, but the form will still stop processing/submitting if the user is already registered for one of the events.

A solution would be to have a setting on the Participant processor to ignore the Event settings, but this could have bad implications, specially for paid events.

**Comment by kapn1966** [comment]
Thanks for your help. Unfortunately, I've had to abandon this way of registering participants for workshops as it doesn't seem to respect the registration limits for an event.

**Comment by mecachisenros** [comment]
@kapn1966 what do you mean with 'it doesn't respect the registration limits'? 

It doesn't show the message 'This event is full' when reaching the max number of participants?
