### ISSUE TITLE
Cannot upload files to CIVICRM (Stuck in submission)

### ISSUE THREAD

**Issue by clement8888** [mecachisenros/cf-civicrm#132]
**Describe the bug**
Created a simple form that submits well without including a file, but would be stuck in submission when a file is chosen and submitted
However, when the record is checked in the CIVICRM, it would be created with the fields in the form, including the file is attached to the record as well.
In a longer form that has processors to link relationships, Contact1 would be created with the fields and the uploaded file but the remaining processors (e.g Relationship) doesn't seem to be activated as no relationships are created in the record.

**To Reproduce**
Created simple form to enter into CIVICRM, included a file upload field
Can submit successfully without including a file
Stuck in submission when a file is chosen for upload

**Expected behavior**
Files should be submitted ok into CIVICRM

**Server (please complete the following information):**
WordPress Version: 5.0.7
PHP Version: 7.2.24-0
ubuntu0.18.04.1
MySQL Version: 5.7.27 
Caldera Forms Version: 1.8.7. 
CF CIVICRM 1.04

**Additional context**
There was no WP_DEBUG error on the server but on the client side, my Chrome browser complained the following when uploading files, there was no error when file is not uploaded:

css:1 Failed to load resource: the server responded with a status of 400 ()
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
/cf-api/CF5d230ed012b32:1 Failed to load resource: the server responded with a status of 500 ()
caldera-forms-front.min.js?ver=1.8.7:1 Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.error (caldera-forms-front.min.js?ver=1.8.7:1)
    at Object.request_error (jquery-baldrick.min.js?ver=1.8.7:1)
    at c (jquery-baldrick.min.js?ver=1.8.7:1)
    at Object.error (jquery-baldrick.min.js?ver=1.8.7:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4:2)
    at x (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
error @ caldera-forms-front.min.js?ver=1.8.7:1
request_error @ jquery-baldrick.min.js?ver=1.8.7:1
c @ jquery-baldrick.min.js?ver=1.8.7:1
error @ jquery-baldrick.min.js?ver=1.8.7:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
x @ jquery.js?ver=1.12.4:4
c @ jquery.js?ver=1.12.4:4
css:1 Failed to load resource: the server responded with a status of 400 ()

**Comment by mecachisenros** [comment]
@clement8888 can you test the latest `dev` branch and confirm if it foxes the issue, it must include this commit dab0d52

**Comment by clement8888** [comment]
> @clement8888 can you test the latest `dev` branch and confirm if it fixes the issue, it must include this commit [dab0d52](https://github.com/mecachisenros/cf-civicrm/commit/dab0d52a94234fb7bcd57df1d94702dd6a4f2ed9)

Hello, it's my first time including a commit, it is essentially adding the code in red into the file processors/contact/class-contact-processor.php  right?

If so, then unfortuantely it still didn't work, the error on the browser side is as follows:

(index):36 GET https://fonts.googleapis.com/css?family=%3A%26amp%3B net::ERR_ABORTED 400
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
jquery.js?ver=1.12.4:4 POST 
https://xxxxxx.com/cf-api/CF5dc4fea75469f 500
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
request @ jquery-baldrick.min.js?ver=1.8.7:1
c @ jquery-baldrick.min.js?ver=1.8.7:1
(anonymous) @ jquery-baldrick.min.js?ver=1.8.7:1
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
caldera-forms-front.min.js?ver=1.8.7:1 Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.error (caldera-forms-front.min.js?ver=1.8.7:1)
    at Object.request_error (jquery-baldrick.min.js?ver=1.8.7:1)
    at c (jquery-baldrick.min.js?ver=1.8.7:1)
    at Object.error (jquery-baldrick.min.js?ver=1.8.7:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4:2)
    at x (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)
error @ caldera-forms-front.min.js?ver=1.8.7:1
request_error @ jquery-baldrick.min.js?ver=1.8.7:1
c @ jquery-baldrick.min.js?ver=1.8.7:1
error @ jquery-baldrick.min.js?ver=1.8.7:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
x @ jquery.js?ver=1.12.4:4
c @ jquery.js?ver=1.12.4:4
XMLHttpRequest.send (async)
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
request @ jquery-baldrick.min.js?ver=1.8.7:1
c @ jquery-baldrick.min.js?ver=1.8.7:1
(anonymous) @ jquery-baldrick.min.js?ver=1.8.7:1
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3

**Comment by mecachisenros** [comment]
@clement8888 

> it is essentially adding the code in red into the file 

nope, the code highlighted in red is a deletion :)

The best way to test would be to download the `dev` branch as zip file (click [here](https://github.com/mecachisenros/cf-civicrm/archive/dev.zip)), deactivate and delete your current CF CiviCRM version, and upload and activate the version you just downloaded, you can do all that from plugins page, Plugins -> Add new -> Upload Plugin.
