### ISSUE TITLE
auto-populate forms with more than one household-member

### ISSUE THREAD

**Issue by Landhead** [mecachisenros/cf-civicrm#133]
Hi, thanks for the development of this nice plugin! 

For a Wordpress-website I have user-accounts for each 'household' registered in CiviCRM. I want to give the Wordpress-user (indeed, the household-account) the ability to check and change the data of all the contacts with a relationship to that household. Therefore it would be nice to show the data that is available in CiviCRM, using the auto-populate features. 

I managed to auto-populate the form using the processors for contact and relationship. But only the first member (first record in CiviCRM) of the Household shows up in the form. I do not see the possibility to select the next records of the CiviCRM data in the processor to auto-populate the form. Am I right that this function is not build in? I would appreciate this feature!

**Comment by CoreyBurger** [comment]
Looks like there is a draft method to do this via custom queries: https://github.com/mecachisenros/cf-civicrm/pull/85

**Comment by mecachisenros** [comment]
@Landhead glad you find the plugin useful!

This feature was not implemented, but it should be now, meaning that auto-population of multiple relationship of the same type should work. 

If you can test the `dev` branch would be great, you can download the latest `dev` version [here](https://github.com/mecachisenros/cf-civicrm/archive/dev.zip).

@CoreyBurger the reference PR has some securities implications (it would allow anyone to query Contacts adding the `?pid=<contact_id>` query), and I don't think it's a suitable solution.

**Comment by CoreyBurger** [comment]
Question regarding the dev version - does it work for both Household -> Contact relationships as well as Contact -> Contact relationships?

**Comment by Landhead** [comment]
@mecachisenros Thanks for your reply!

I've tested the dev-version.  I'm sorry, but unfortunately it is still not working for me. Each new field that I add for the next member of the household (including off course the necessary contact and relationship processor) gives me the same record. Only the first record of the relationship type 'Household member' shows up. My goal is to have all the records in the form, sorted on date of membership.

![image](https://user-images.githubusercontent.com/57446017/68894285-4884c080-0727-11ea-83ca-48231d3eb9b7.png)

**Comment by mecachisenros** [comment]
@Landhead can you try again the latest `dev` branch, it should be fixed now via ae9527a49922fe199aa46c5dcd13082026410aef.

<img width="541" alt="household_to_individual" src="https://user-images.githubusercontent.com/3038096/69547107-e7fa4c80-0f8c-11ea-84d9-1d1becee61e6.png">

@CoreyBurger yes, it should work for both directions.

<img width="560" alt="individual_to_individual" src="https://user-images.githubusercontent.com/3038096/69547188-05c7b180-0f8d-11ea-8721-c081f4a60480.png">

**Note**, if you are using multiple relationship types, you must order them/group them toghether consecutively.

<img width="848" alt="relationship_group" src="https://user-images.githubusercontent.com/3038096/69547971-65728c80-0f8e-11ea-92f4-144aba483c95.png">

**Comment by CoreyBurger** [comment]
That's fantastic. I only have my production environment, so cannot test but looking forward to it
