### ISSUE TITLE
Don't see the CIVICRM processors in the processors list 

### ISSUE THREAD

**Issue by alexmbb** [mecachisenros/cf-civicrm#145]
Installed the caldera forms and the cf-civicrm plugins
Created a form and when adding a processor I don't see there any processors related to civicrm
Is there any additional settings that I miss?
https://tinyurl.com/sppyq32

**Comment by elliottmart** [comment]
If you add a contact processor you should see the forms at bottom of that screen. Click on them eg. Custom Fields to expose the Civi fields to map to. Put magic fields in the Civi fields to match your caldera fields to civi. eg %my-caldera-field% in your civi custom field. Write back to me if you have a problem.
