### ISSUE TITLE
How does one populate existing contact information for an arbitrary contact ID?

### ISSUE THREAD

**Issue by mwittmann** [mecachisenros/cf-civicrm#147]
I'd like to be able to use Caldera Forms CiviCRM to edit the information for an existing contact who is _not_ the logged in user. 

How can I automatically populate the form with another contact's information? How could the contact ID be passed as a parameter?

**Comment by mecachisenros** [comment]
This will be available in the next release, or you can test on the current `dev` branch.

You can add the contact ID as a query arg to the url where you have the form i.e. `cid=123` where `123` is the contact ID, for example if your form is at `https://example.org/some-page` you would add the query arg like so `https://example.org/some-page/?cid=123`.

If you have enough permissions to edit that contact it will auto populate its data and you should be able to update it.
