### ISSUE TITLE
Caldera version not clear in WP readme. 

### ISSUE THREAD

**Issue by twocs** [mecachisenros/cf-civicrm#156]
**Describe the bug**

The [readme.txt](https://github.com/mecachisenros/cf-civicrm/blob/master/readme.txt) is vague about the necessary version of Caldera Forms. It says simply:
> This plugin requires a minimum of CiviCRM 4.6 although the latest version is recommended, and Caldera Forms 1.8.1.

Caldera Forms is currently at 1.8.11. So is it a minimum of Caldera 1.8.1? Or only Caldera Forms 1.8.1 will be acceptable, no higher?

**Expected behavior**
Can the wording be clearer? Either:

This plugin requires a minimum of CiviCRM 4.6, although the latest version is recommended, and a minimum of Caldera Forms 1.8.1 (the latest version is recommended).

This plugin requires a minimum of CiviCRM 4.6, although the latest version is recommended, and Caldera Forms 1.8.1 (later version of Caldera Forms have not been tested).

**Comment by elliottmart** [comment]
I'm using it with CF 1.8.11 and it's going well!

**Comment by twocs** [comment]
The Readme now says:
> To use this plugin, the following is needed:
> 
> WordPress
> CiviCRM 5.x
> Caldera Forms v1.8.1 or greater to be installed

I think this is very clear now.
