### ISSUE TITLE
ETA for Events Processor

### ISSUE THREAD

**Issue by seascoot** [mecachisenros/cf-civicrm#25]
Hi @mecachisenros,

I'm so stoked that you are doing this!  Do you have an idea of when you may get to an Events processor?  It is essential for my anticipated use.

Finally we may be getting close to an equivalent to Webform Civicrm on Wordpress.

**Comment by mecachisenros** [comment]
Hi @seascoot 

Glad you like the integration. I'm afraid I cannot give you an ETA, the main problem we are trying to figure out is how to handle payments, once that is done Participant, Memberships, Donations and Contributions processors will follow. 

I could add a Participant processor now but it will only work for **free** events.

Also if you have any feedback or issues/bugs that you might find please report back here.

**Comment by seascoot** [comment]
I will certainly report back on my testing.

I don't actually need a payment processor right now.  I am using the Woocommerce cart for payments.  I just need to record participants as "Pending (pay later)" (and maybe assign memberships based on event and relationship) in Civi.  For now I can just manually confirm payment received in Civi based on my WC order status.

**Comment by Numinous** [comment]
Hello @mecachisenros!  Thanks for the outstanding work. In regards to handling payments, some of the work done by veda consulting may be helpful.   [(https://github.com/veda-consulting/woocommerce_civicrm)](url)  I feel like handling payments attractively and seamlessly through forms would solve the most glaring deficiency of Civi on Wordpress.  A professional and enticing front-end for donating or purchasing is absolutely vital for many reasons.
