### ISSUE TITLE
Auto Populate Parent Organization information if logged in

### ISSUE THREAD

**Issue by paulsyhand** [mecachisenros/cf-civicrm#69]
Hi,
Don't know if this is an issue, or user error, but I'm trying to figure out if this plugin will auto populate the users Parent organization information. I can get the form to update the organization info when the form is submitted, but need to display what is already in Civi. Is this possible? Thanks!

**Comment by mecachisenros** [comment]
Hi @paulsyhand if I understand correctly you want to auto populate data (like an address or custom fields) for a related contact ie Current Employer, that's currently not implemented (but it can be).

So to answer your question, no, it's currently not possible :)

Auto population (for now) only works for the first Contact processor (Contact 1).

**Comment by paulsyhand** [comment]
Thanks @mecachisenros for your feedback. Yes exactly what I was inquiring about.

**Comment by mecachisenros** [comment]
@paulsyhand this has been implemented in v1.0.4
